# permissions for end users to edit tzcronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tzcronjob-editor-role
rules:
- apiGroups:
  - tzcronjob.github.com
  resources:
  - tzcronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tzcronjob.github.com
  resources:
  - tzcronjobs/status
  verbs:
  - get
