apiVersion: tzcronjob.github.com/v1
kind: TZCronjob
metadata:
  name: tzcronjob-sample
spec:
  schedule: "*/1 * * * *"
  timezone: "Europe/Amsterdam"
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo "Hello, World!"
          restartPolicy: OnFailure